version: "3.9"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      - "mysql_DATABASE=<YOUR_DBNAME_HERE>"
    env_file:
      - mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql

  webserver:
    build: ./<YOUR_SERVER_DIRECTORY>
    container_name: webserver
    depends_on:
      mysql:
    env_file:
      - mysql/.env
      - <YOUR_SERVER_DIRECTORY>/.env

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - webserver

volumes:
  mysql_data:
    name: "file_db"